spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tlamatini
  username: tlamatini
  password: secret

spring.jpa:
  show-sql: true
  properties.hibernate.format_sql: true